version: '3'

services:
  # Prosody server (XMPP)
  prosody:
    image: jitsi/prosody
    container_name: prosody
    restart: always
    environment:
      - XMPP_DOMAIN=sh1bari.ru
      - XMPP_PORT=5222
      - PUBLIC_URL=https://sh1bari.ru
      - CERTS_DIR=/certs
    volumes:
      - ./config/prosody:/config
    networks:
      - jitsi-network

  # Jicofo server (Focus component)
  jicofo:
    image: jitsi/jicofo
    container_name: jicofo
    restart: always
    depends_on:
      - prosody
      - jitsi-videobridge
    environment:
      - XMPP_DOMAIN=sh1bari.ru
      - JICOFO_HOST=jicofo
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=password
      - XMPP_SERVER=prosody
    volumes:
      - ./config/jicofo:/config
    networks:
      - jitsi-network

  # Jitsi Videobridge (Video component)
  jitsi-videobridge:
    image: jitsi/jitsi-videobridge
    container_name: jitsi-videobridge
    restart: always
    environment:
      - XMPP_SERVER=prosody
      - JVB_HOST=jitsi-videobridge
      - JVB_SECRET=secret
      - JVB_PORT=10000
      - JVB_STUN_SERVERS=stun:sh1bari.ru:3478
    volumes:
      - ./config/jvb:/config
    networks:
      - jitsi-network

networks:
  jitsi-network:
    driver: bridge
